// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSpYXLxJNIWMUN4etZS9iSgw1Avn7ChYg',
    appId: '1:1092995006432:web:1755130193517752f13585',
    messagingSenderId: '1092995006432',
    projectId: 'flutter-project-41fe3',
    authDomain: 'flutter-project-41fe3.firebaseapp.com',
    storageBucket: 'flutter-project-41fe3.firebasestorage.app',
    measurementId: 'G-P1CJCVN8RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3rxJAiG-kB34p3R_QPjs-zPVVuI3K0cw',
    appId: '1:1092995006432:android:14b10fb30c877d96f13585',
    messagingSenderId: '1092995006432',
    projectId: 'flutter-project-41fe3',
    storageBucket: 'flutter-project-41fe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF9Gl2Hvdx2WfaOAkNR-Lv3cXIwmPokMg',
    appId: '1:1092995006432:ios:1c343adfcde6c287f13585',
    messagingSenderId: '1092995006432',
    projectId: 'flutter-project-41fe3',
    storageBucket: 'flutter-project-41fe3.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF9Gl2Hvdx2WfaOAkNR-Lv3cXIwmPokMg',
    appId: '1:1092995006432:ios:1c343adfcde6c287f13585',
    messagingSenderId: '1092995006432',
    projectId: 'flutter-project-41fe3',
    storageBucket: 'flutter-project-41fe3.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSpYXLxJNIWMUN4etZS9iSgw1Avn7ChYg',
    appId: '1:1092995006432:web:28dbeb862037dd09f13585',
    messagingSenderId: '1092995006432',
    projectId: 'flutter-project-41fe3',
    authDomain: 'flutter-project-41fe3.firebaseapp.com',
    storageBucket: 'flutter-project-41fe3.firebasestorage.app',
    measurementId: 'G-QW1QMMEN5T',
  );
}
